### PR TITLE
fake player left message

### PR DESCRIPTION
**Pull request by DadoIrie**
message when a fake player left

### CODE REVIEW

**Comment by SurfingDude-1182** [comment]
Something to possibly add to this, check if type of player is 'shadow' and have a shadow player joining and leaving message

**Review by pseudofractal — CHANGES_REQUESTED** [review]
Something to possibly add to this, check if type of player is 'shadow' and have a shadow player joining and leaving message.

**Comment by DadoIrie** [comment]
I don't even understand what a shadow player is 🤣 fake player? That's this here

**Comment by pseudofractal** [comment]
> I don't even understand what a shadow player is rofl fake player? That's this here

Oh...

**Pull request merged**
